services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: forum_pg_test
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}