services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: forum_pg_dev
    ports:
      - '5432:${DB_PORT}'
    env_file:
      - .env.development
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: bitnami/redis:latest
    container_name: forum_redis
    ports:
      - "6379:6379"