services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: forum_pg_test
    ports:
      - '${DB_PORT}:5432'
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: bitnami/redis:latest
    container_name: forum_redis_test
    ports:
      - '${REDIS_PORT}:6379'
    env_file:
      - .env.test
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}